site_name: Bits & Pieces
site_url: https://rejasupotaro.github.io/
site_author: Rejasupotaro
site_description: Personal blog about anything

theme:
  name: shadcn
  show_title: true
  show_stargazers: false
  pygments_style:
    light: shadcn-light
    dark: github-dark
  icon: heroicons:rocket-launch
  show_datetime: false
  topbar_sections: true

plugins:
  - search
  - excalidraw
  - mkdocstrings

markdown_extensions:
  admonition:
  codehilite:
  fenced_code:
  footnotes:
  extra:
  pymdownx.blocks.details:
  pymdownx.tabbed:
  pymdownx.blocks.tab:
    combine_header_slug: true
    separator: ___
  pymdownx.progressbar:
  pymdownx.snippets:
  pymdownx.arithmatex:
    generic: true
  shadcn.extensions.echarts.alpha:
  shadcn.extensions.codexec:
  shadcn.extensions.iconify:
  pymdownx.blocks.caption:

nav:
  - Home: index.md
  - Blog:
    - Embedding: posts/embedding-evaluation-survey.md
